import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import htmlImg from '../assets/img/html.png';
import cssImg from '../assets/img/css.png';
import jsImg from '../assets/img/javascript.png';
import reactImg from '../assets/img/react.png';
import angularImg from '../assets/img/angular.png';
import tailwindImg from '../assets/img/tailwind.png';
import mysqlImg from '../assets/img/mysql2.png';
import nodejs from '../assets/img/nodejs.png';
const Skills = () => {
    return (_jsxs("div", { className: 'bg-black border border-gray-600 text-gray-400 md:h-[150px] max-w-[1200px] mx-auto grid grid-cols-6\r\n      place-items-center md:flex md:justify-between md:items-center', children: [_jsxs("h2", { className: 'text-gray-700 text-xl md:text-4xl font-bold m-4', children: ["My ", _jsx("br", {}), " Tech ", _jsx("br", {}), " Stack"] }), _jsxs("div", { className: 'flex flex-col items-center m-4 sm:my-0 w-[80px] md:w-[100px]', children: [_jsx("img", { src: jsImg, alt: '', className: "w-24 h-24 object-contain" }), _jsx("p", { className: 'mt-2', children: "Javascript" })] }), _jsxs("div", { className: 'flex flex-col items-center m-4 sm:my-0 w-[80px] md:w-[100px]', children: [_jsx("img", { src: nodejs, alt: '', className: "w-24 h-24 object-contain" }), _jsx("p", { className: 'mt-2', children: "NodeJs" })] }), _jsxs("div", { className: 'flex flex-col items-center m-4 sm:my-0 w-[80px] md:w-[100px]', children: [_jsx("img", { src: angularImg, alt: '', className: "w-24 h-24 object-contain" }), _jsx("p", { className: 'mt-2', children: "Angular" })] }), _jsxs("div", { className: 'flex flex-col items-center m-4 sm:my-0 w-[80px] md:w-[100px]', children: [_jsx("img", { src: reactImg, alt: '', className: "w-24 h-24 object-contain" }), _jsx("p", { className: 'mt-2', children: "React" })] }), _jsxs("div", { className: 'flex flex-col items-center m-4 sm:my-0 w-[80px] md:w-[100px]', children: [_jsx("img", { src: mysqlImg, alt: '', className: "w-24 h-24 object-contain" }), _jsx("p", { className: 'mt-2', children: "MySql" })] }), _jsxs("div", { className: 'flex flex-col items-center m-4 sm:my-0 w-[80px] md:w-[100px]', children: [_jsx("img", { src: htmlImg, alt: '', className: "w-24 h-24 object-contain" }), _jsx("p", { className: 'mt-2', children: "HTML" })] }), _jsxs("div", { className: 'flex flex-col items-center m-4 sm:my-0 w-[80px] md:w-[100px]', children: [_jsx("img", { src: cssImg, alt: '', className: "w-24 h-24 object-contain" }), _jsx("p", { className: 'mt-2', children: "CSS" })] }), _jsxs("div", { className: 'flex flex-col items-center m-4 sm:my-0 w-[80px] md:w-[100px]', children: [_jsx("img", { src: tailwindImg, alt: '', className: "w-24 h-24 object-contain" }), _jsx("p", { className: 'mt-2', children: "Tailwind" })] })] }));
};
export default Skills;
